FROM python:3.6.5-alpine

WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/requirements.txt
#RUN apk update && \
#    apk add --no-cache --virtual build-deps gcc python-dev musl-dev && \
#    apk add --no-cache postgresql-dev && \
#    apk add --no-cache --virtual build-deps netcat-openbsd libffi-dev libffi

RUN pip --no-cache-dir install -r requirements.txt
#RUN apk del build-deps
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod 777 /usr/src/app/entrypoint-prod.sh

COPY . /usr/src/app
CMD ["/usr/src/app/entrypoint-prod.sh"]