version: '3.6'

services:
  core:
    build:
      context: ./services/core
      dockerfile: Dockerfile-dev
    volumes:
      - './services/core:/usr/src/app'
    ports:
      - 5000:5000
    env_file:
      - .env