version: '3.6'

services:
  core:
    build:
      context: ./services/core
      dockerfile: Dockerfile-prod
    volumes:
      - "${ROOT}/services/core:/usr/src/app"
    ports:
      - 5000:5000
    env_file:
      - .env

  nginx:
    build:
      context: services/nginx/prod
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${ROOT}/services/nginx/prod:/etc/nginx/conf.d"
      - "${ROOT}/services/certbot/conf:/etc/letsencrypt"
      - "${ROOT}/services/certbot/www:/var/www/certbot"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - core

  certbot:
    image: certbot/certbot
    volumes:
      - "${ROOT}/services/certbot/conf:/etc/letsencrypt"
      - "${ROOT}/services/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
