version: '3.6'

services:
  core:
    build:
      context: ./services/core
      dockerfile: Dockerfile-dev
    volumes:
      - './services/core:/usr/src/app'
    ports:
      - 5000:5000
    env_file:
      - .env-dev

  nginx:
    build:
      context: services/nginx/dev
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - core

  core-db:
    build:
      context: ./services/core/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - .env-dev